DROP DATABASE IF EXISTS enterprise_sql_lab;
CREATE DATABASE enterprise_sql_lab;
\connect enterprise_sql_lab

DROP TABLE IF EXISTS auditoria_eventos CASCADE;
DROP TABLE IF EXISTS resenas CASCADE;
DROP TABLE IF EXISTS devoluciones CASCADE;
DROP TABLE IF EXISTS envios CASCADE;
DROP TABLE IF EXISTS pagos CASCADE;
DROP TABLE IF EXISTS detalle_pedidos CASCADE;
DROP TABLE IF EXISTS pedido_cupones CASCADE;
DROP TABLE IF EXISTS pedidos CASCADE;
DROP TABLE IF EXISTS inventario CASCADE;
DROP TABLE IF EXISTS productos CASCADE;
DROP TABLE IF EXISTS categorias CASCADE;
DROP TABLE IF EXISTS proveedores CASCADE;
DROP TABLE IF EXISTS cupones CASCADE;
DROP TABLE IF EXISTS direcciones CASCADE;
DROP TABLE IF EXISTS clientes CASCADE;
DROP TABLE IF EXISTS empleados CASCADE;
DROP TABLE IF EXISTS sucursales CASCADE;
DROP TABLE IF EXISTS ciudades CASCADE;

DROP TYPE IF EXISTS empleado_cargo CASCADE;
DROP TYPE IF EXISTS tipo_documento_cliente CASCADE;
DROP TYPE IF EXISTS nivel_fidelidad_cliente CASCADE;
DROP TYPE IF EXISTS tipo_descuento_cupon CASCADE;
DROP TYPE IF EXISTS estado_pedido CASCADE;
DROP TYPE IF EXISTS metodo_pago_tipo CASCADE;
DROP TYPE IF EXISTS estado_pago_tipo CASCADE;
DROP TYPE IF EXISTS estado_envio_tipo CASCADE;
DROP TYPE IF EXISTS motivo_devolucion_tipo CASCADE;
DROP TYPE IF EXISTS estado_devolucion_tipo CASCADE;
DROP TYPE IF EXISTS accion_auditoria_tipo CASCADE;

CREATE TYPE empleado_cargo AS ENUM ('asesor_ventas', 'cajero', 'bodega', 'soporte', 'gerente');
CREATE TYPE tipo_documento_cliente AS ENUM ('CC', 'CE', 'NIT', 'PASAPORTE');
CREATE TYPE nivel_fidelidad_cliente AS ENUM ('bronce', 'plata', 'oro', 'platino');
CREATE TYPE tipo_descuento_cupon AS ENUM ('porcentaje', 'valor_fijo');
CREATE TYPE estado_pedido AS ENUM ('creado', 'pagado', 'enviado', 'entregado', 'cancelado', 'devuelto');
CREATE TYPE metodo_pago_tipo AS ENUM ('tarjeta_credito', 'tarjeta_debito', 'pse', 'transferencia', 'efectivo', 'wallet');
CREATE TYPE estado_pago_tipo AS ENUM ('pendiente', 'aprobado', 'rechazado', 'reversado');
CREATE TYPE estado_envio_tipo AS ENUM ('preparando', 'en_transito', 'entregado', 'devuelto');
CREATE TYPE motivo_devolucion_tipo AS ENUM ('producto_defectuoso', 'no_corresponde', 'arrepentimiento', 'demora_entrega', 'otro');
CREATE TYPE estado_devolucion_tipo AS ENUM ('solicitada', 'aprobada', 'rechazada', 'reembolsada');
CREATE TYPE accion_auditoria_tipo AS ENUM ('insert', 'update', 'delete', 'estado');

CREATE TABLE ciudades (
  ciudad_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(80) NOT NULL,
  departamento_estado VARCHAR(80) NOT NULL,
  pais VARCHAR(80) NOT NULL,
  codigo_dane VARCHAR(10) NULL,
  CONSTRAINT uk_ciudad_region_pais UNIQUE (nombre, departamento_estado, pais)
);

CREATE TABLE sucursales (
  sucursal_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(120) NOT NULL,
  ciudad_id INTEGER NOT NULL,
  direccion VARCHAR(180) NOT NULL,
  telefono VARCHAR(25) NOT NULL,
  fecha_apertura DATE NOT NULL,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uk_sucursal_nombre UNIQUE (nombre),
  CONSTRAINT fk_sucursal_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudades(ciudad_id),
  CONSTRAINT chk_sucursal_fecha CHECK (fecha_apertura >= DATE '2000-01-01')
);

CREATE TABLE empleados (
  empleado_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursal_id INTEGER NOT NULL,
  nombres VARCHAR(90) NOT NULL,
  apellidos VARCHAR(90) NOT NULL,
  email VARCHAR(140) NOT NULL,
  telefono VARCHAR(25) NOT NULL,
  cargo empleado_cargo NOT NULL,
  salario_mensual NUMERIC(12,2) NOT NULL,
  fecha_contratacion DATE NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uk_empleado_email UNIQUE (email),
  CONSTRAINT fk_empleado_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(sucursal_id),
  CONSTRAINT chk_empleado_salario CHECK (salario_mensual > 0),
  CONSTRAINT chk_empleado_fecha CHECK (fecha_contratacion >= DATE '2010-01-01')
);

CREATE TABLE clientes (
  cliente_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tipo_documento tipo_documento_cliente NOT NULL,
  numero_documento VARCHAR(30) NOT NULL,
  nombres VARCHAR(90) NOT NULL,
  apellidos VARCHAR(90) NOT NULL,
  email VARCHAR(140) NOT NULL,
  telefono VARCHAR(25) NOT NULL,
  fecha_nacimiento DATE NULL,
  fecha_registro TIMESTAMP NOT NULL,
  nivel_fidelidad nivel_fidelidad_cliente NOT NULL DEFAULT 'bronce',
  acepta_marketing BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uk_cliente_documento UNIQUE (tipo_documento, numero_documento),
  CONSTRAINT uk_cliente_email UNIQUE (email),
  CONSTRAINT chk_cliente_fecha_registro CHECK (fecha_registro >= TIMESTAMP '2018-01-01 00:00:00')
);

CREATE TABLE direcciones (
  direccion_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INTEGER NOT NULL,
  ciudad_id INTEGER NOT NULL,
  linea_1 VARCHAR(180) NOT NULL,
  linea_2 VARCHAR(180) NULL,
  codigo_postal VARCHAR(20) NULL,
  referencia VARCHAR(180) NULL,
  es_principal BOOLEAN NOT NULL DEFAULT FALSE,
  CONSTRAINT fk_direccion_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(cliente_id),
  CONSTRAINT fk_direccion_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudades(ciudad_id)
);

CREATE TABLE proveedores (
  proveedor_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(140) NOT NULL,
  contacto_nombre VARCHAR(120) NOT NULL,
  email VARCHAR(140) NOT NULL,
  telefono VARCHAR(25) NOT NULL,
  ciudad_id INTEGER NOT NULL,
  tiempo_entrega_dias SMALLINT NOT NULL DEFAULT 5,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uk_proveedor_nombre UNIQUE (nombre),
  CONSTRAINT uk_proveedor_email UNIQUE (email),
  CONSTRAINT fk_proveedor_ciudad FOREIGN KEY (ciudad_id) REFERENCES ciudades(ciudad_id),
  CONSTRAINT chk_proveedor_tiempo CHECK (tiempo_entrega_dias BETWEEN 1 AND 30)
);

CREATE TABLE categorias (
  categoria_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_padre_id INTEGER NULL,
  nombre VARCHAR(120) NOT NULL,
  descripcion VARCHAR(255) NULL,
  activa BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uk_categoria_nombre UNIQUE (nombre),
  CONSTRAINT fk_categoria_padre FOREIGN KEY (categoria_padre_id) REFERENCES categorias(categoria_id)
);

CREATE TABLE productos (
  producto_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  categoria_id INTEGER NOT NULL,
  proveedor_id INTEGER NOT NULL,
  sku VARCHAR(30) NOT NULL,
  nombre VARCHAR(140) NOT NULL,
  descripcion VARCHAR(255) NULL,
  precio_venta NUMERIC(12,2) NOT NULL,
  costo_unitario NUMERIC(12,2) NOT NULL,
  peso_kg NUMERIC(8,3) NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  fecha_alta TIMESTAMP NOT NULL,
  CONSTRAINT uk_producto_sku UNIQUE (sku),
  CONSTRAINT fk_producto_categoria FOREIGN KEY (categoria_id) REFERENCES categorias(categoria_id),
  CONSTRAINT fk_producto_proveedor FOREIGN KEY (proveedor_id) REFERENCES proveedores(proveedor_id),
  CONSTRAINT chk_producto_precio CHECK (precio_venta > 0),
  CONSTRAINT chk_producto_costo CHECK (costo_unitario > 0),
  CONSTRAINT chk_producto_margen CHECK (precio_venta >= costo_unitario),
  CONSTRAINT chk_producto_peso CHECK (peso_kg > 0)
);

CREATE TABLE inventario (
  inventario_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  sucursal_id INTEGER NOT NULL,
  producto_id INTEGER NOT NULL,
  stock_actual INTEGER NOT NULL,
  stock_minimo INTEGER NOT NULL,
  stock_maximo INTEGER NOT NULL,
  punto_reorden INTEGER NOT NULL,
  fecha_actualizacion TIMESTAMP NOT NULL,
  CONSTRAINT uk_inventario_sucursal_producto UNIQUE (sucursal_id, producto_id),
  CONSTRAINT fk_inventario_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(sucursal_id),
  CONSTRAINT fk_inventario_producto FOREIGN KEY (producto_id) REFERENCES productos(producto_id),
  CONSTRAINT chk_inventario_stock CHECK (stock_actual >= 0),
  CONSTRAINT chk_inventario_min_max CHECK (stock_minimo >= 0 AND stock_maximo >= stock_minimo),
  CONSTRAINT chk_inventario_reorden CHECK (punto_reorden BETWEEN stock_minimo AND stock_maximo)
);

CREATE TABLE cupones (
  cupon_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  codigo VARCHAR(40) NOT NULL,
  descripcion VARCHAR(180) NOT NULL,
  tipo_descuento tipo_descuento_cupon NOT NULL,
  valor_descuento NUMERIC(10,2) NOT NULL,
  monto_minimo NUMERIC(10,2) NOT NULL DEFAULT 0,
  fecha_inicio DATE NOT NULL,
  fecha_fin DATE NOT NULL,
  uso_maximo INTEGER NOT NULL,
  activo BOOLEAN NOT NULL DEFAULT TRUE,
  CONSTRAINT uk_cupon_codigo UNIQUE (codigo),
  CONSTRAINT chk_cupon_valor CHECK (valor_descuento > 0),
  CONSTRAINT chk_cupon_fechas CHECK (fecha_fin >= fecha_inicio)
);

CREATE TABLE pedidos (
  pedido_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cliente_id INTEGER NOT NULL,
  direccion_envio_id INTEGER NOT NULL,
  empleado_id INTEGER NULL,
  sucursal_id INTEGER NOT NULL,
  fecha_pedido TIMESTAMP NOT NULL,
  estado estado_pedido NOT NULL,
  subtotal NUMERIC(12,2) NOT NULL DEFAULT 0,
  descuento_total NUMERIC(12,2) NOT NULL DEFAULT 0,
  costo_logistico NUMERIC(12,2) NOT NULL DEFAULT 0,
  total NUMERIC(12,2) NOT NULL DEFAULT 0,
  observaciones VARCHAR(255) NULL,
  CONSTRAINT fk_pedido_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(cliente_id),
  CONSTRAINT fk_pedido_direccion FOREIGN KEY (direccion_envio_id) REFERENCES direcciones(direccion_id),
  CONSTRAINT fk_pedido_empleado FOREIGN KEY (empleado_id) REFERENCES empleados(empleado_id),
  CONSTRAINT fk_pedido_sucursal FOREIGN KEY (sucursal_id) REFERENCES sucursales(sucursal_id),
  CONSTRAINT chk_pedido_montos CHECK (
    subtotal >= 0
    AND descuento_total >= 0
    AND costo_logistico >= 0
    AND total >= 0
  )
);

CREATE TABLE pedido_cupones (
  pedido_cupon_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  cupon_id INTEGER NOT NULL,
  valor_aplicado NUMERIC(12,2) NOT NULL,
  CONSTRAINT fk_pedido_cupon_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(pedido_id),
  CONSTRAINT fk_pedido_cupon_cupon FOREIGN KEY (cupon_id) REFERENCES cupones(cupon_id),
  CONSTRAINT uk_pedido_cupon_unico UNIQUE (pedido_id, cupon_id),
  CONSTRAINT chk_pedido_cupon_valor CHECK (valor_aplicado >= 0)
);

CREATE TABLE detalle_pedidos (
  detalle_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  producto_id INTEGER NOT NULL,
  cantidad INTEGER NOT NULL,
  precio_unitario NUMERIC(12,2) NOT NULL,
  descuento_unitario NUMERIC(12,2) NOT NULL DEFAULT 0,
  impuesto_unitario NUMERIC(12,2) NOT NULL DEFAULT 0,
  CONSTRAINT fk_detalle_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(pedido_id),
  CONSTRAINT fk_detalle_producto FOREIGN KEY (producto_id) REFERENCES productos(producto_id),
  CONSTRAINT chk_detalle_cantidad CHECK (cantidad > 0),
  CONSTRAINT chk_detalle_precio CHECK (precio_unitario > 0),
  CONSTRAINT chk_detalle_descuento CHECK (descuento_unitario >= 0),
  CONSTRAINT chk_detalle_impuesto CHECK (impuesto_unitario >= 0)
);

CREATE TABLE pagos (
  pago_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  fecha_pago TIMESTAMP NOT NULL,
  metodo_pago metodo_pago_tipo NOT NULL,
  estado_pago estado_pago_tipo NOT NULL,
  monto NUMERIC(12,2) NOT NULL,
  referencia_externa VARCHAR(80) NULL,
  CONSTRAINT fk_pago_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(pedido_id),
  CONSTRAINT chk_pago_monto CHECK (monto >= 0)
);

CREATE TABLE envios (
  envio_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  transportadora VARCHAR(90) NOT NULL,
  numero_guia VARCHAR(80) NULL,
  fecha_envio TIMESTAMP NOT NULL,
  fecha_entrega_estimada TIMESTAMP NOT NULL,
  fecha_entrega_real TIMESTAMP NULL,
  estado_envio estado_envio_tipo NOT NULL,
  costo_envio NUMERIC(12,2) NOT NULL,
  CONSTRAINT fk_envio_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(pedido_id),
  CONSTRAINT uk_envio_pedido UNIQUE (pedido_id),
  CONSTRAINT chk_envio_costo CHECK (costo_envio >= 0)
);

CREATE TABLE devoluciones (
  devolucion_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  pedido_id BIGINT NOT NULL,
  detalle_id BIGINT NOT NULL,
  fecha_solicitud TIMESTAMP NOT NULL,
  motivo motivo_devolucion_tipo NOT NULL,
  estado estado_devolucion_tipo NOT NULL,
  cantidad INTEGER NOT NULL,
  monto_reembolso NUMERIC(12,2) NOT NULL,
  CONSTRAINT fk_devolucion_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(pedido_id),
  CONSTRAINT fk_devolucion_detalle FOREIGN KEY (detalle_id) REFERENCES detalle_pedidos(detalle_id),
  CONSTRAINT chk_devolucion_cantidad CHECK (cantidad > 0),
  CONSTRAINT chk_devolucion_monto CHECK (monto_reembolso >= 0)
);

CREATE TABLE resenas (
  resena_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  producto_id INTEGER NOT NULL,
  cliente_id INTEGER NOT NULL,
  pedido_id BIGINT NOT NULL,
  puntuacion SMALLINT NOT NULL,
  comentario VARCHAR(255) NULL,
  fecha_resena TIMESTAMP NOT NULL,
  CONSTRAINT fk_resena_producto FOREIGN KEY (producto_id) REFERENCES productos(producto_id),
  CONSTRAINT fk_resena_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(cliente_id),
  CONSTRAINT fk_resena_pedido FOREIGN KEY (pedido_id) REFERENCES pedidos(pedido_id),
  CONSTRAINT chk_resena_puntuacion CHECK (puntuacion BETWEEN 1 AND 5)
);

CREATE TABLE auditoria_eventos (
  evento_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  entidad VARCHAR(60) NOT NULL,
  entidad_id BIGINT NOT NULL,
  accion accion_auditoria_tipo NOT NULL,
  usuario_sistema VARCHAR(80) NOT NULL,
  detalle JSONB NULL,
  fecha_evento TIMESTAMP NOT NULL
);

CREATE INDEX idx_auditoria_entidad_fecha ON auditoria_eventos (entidad, fecha_evento);
